# Project: Lab4-2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Circle.o
LINKOBJ  = main.o Circle.o
LIBS     = -L"E:/Programs/Dev-Cpp/MinGW64/lib" -L"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"E:/Programs/SFML/lib" -static-libgcc
INCS     = -I"E:/Programs/Dev-Cpp/MinGW64/include" -I"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Programs/Dev-Cpp/MinGW64/include" -I"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"E:/Programs/SFML/include"
BIN      = Lab4-2.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Circle.o: Circle.cpp
	$(CPP) -c Circle.cpp -o Circle.o $(CXXFLAGS)
